name: trailbuddy
description: A smart hiking companion app built with Flutter.
publish_to: 'none' # since this is a student/capstone project

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^3.0.0
  riverpod: ^3.0.0

  # Mapping
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

  # Location services
  geolocator: ^14.0.2
  geolocator_windows: ^0.2.5

  # File & storage
  file_picker: ^10.3.3
  path_provider: ^2.1.5
  uuid: ^4.5.1

  # Cupertino icons (default)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Optional: add assets if you need images/icons later
  assets:
    - assets/images/

